### PR TITLE
Create Guide : Using Openstack Tokens

### PR DESCRIPTION
**Pull request by thomasrts**

### CODE REVIEW

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+```
+
+### Step 5: Revoke Openstack token
+
+Once you performed all the actions you wanted, you can revoke used token to avoid it to be used for any other actions
+
+To do so :
+
+```bash
+openstack --os-auth-type token token revoke <token_id>
```
Comment (arnaudmorin) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md:160]: token token?
:)

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+
+# or 
+
+openstack --os-auth-type token token revoke $OS_TOKEN
```
Comment (arnaudmorin) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md:164]: same here

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+```
+
+### Étape 5 : Révoquer le jeton Openstack
+
+Une fois que vous avez effectué toutes les actions que vous souhaitiez, vous pouvez révoquer le token utilisé pour éviter qu'il ne soit utilisé pour d'autres actions.
+
+Pour ce faire :
+
+```bash
+openstack --os-auth-type token token revoke <token_id>
```
Comment (arnaudmorin) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md:158]: token token

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+
+# ou 
+
+openstack --os-auth-type token token revoke $OS_TOKEN
```
Comment (arnaudmorin) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md:162]: same here

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md (hunk 1 above)
Comment (thomasrts) [reply pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md:160]: Yup, I've tried without the --os-auth-type and I've this error : 
openstack token revoke $OS_TOKEN
__init__() got an unexpected keyword argument 'token'

By using the --os-auth-type token, it works perfectly

Comment (arnaudmorin) [reply pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md:160]: Damn, I understand now!
Sorry for this

Comment (aarents) [reply pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md:160]: I was able to get it working on openstack cli version 5.1.2 and 6.0.0, cool

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+
+- Token: A unique string of characters used to authenticate and access resources. The user requests it by entering their credentials (login details) to the authentication API. The token is generated and it is valid for 24 hours.
+
+- OpenRC : To increase efficiency of interactions with the Identity service via the openstack client, OpenStack supports simple client environment scripts also known as OpenRC files.
+This is a file containing common options for all clients, but also support unique options.
+
+### Outline of a request
+Most requests sent to the OpenStack API must follow an authorization procedure, which involves generating a token and validating it.
+
+However, if you perform too much actions in a short time, some Openstack actions will fall in error due to too much API Calls
```
Comment (aarents) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md]: Maybe we can give more information here, like (to be better rephrase) :
The interest reuse a token avoid the cli create one at each command run, make it quicker, and avoid HTTP 429  error because token generation is rate limited to 60 per minute, and other API calls does not have such limit.

**Review by aarents — CHANGES_REQUESTED** [review]
nice doc

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md [hunk 6]
```diff
@@ -0,0 +1,164 @@
...
+
+For more information, see the [OpenStack API](http://developer.openstack.org/api-guide/quick-start/) documentation.
+
+This guide will show you how to issue an Openstack token, use it for the actions you want to perform and how to revoke a token
+
+### Requirements 
+
+This guide needs the Openstack CLI tool installed on your machine
+
+You can find more informations on this tool with this guide : [OpenStack CLI](https://docs.openstack.org/newton/user-guide/cli.html)
```
Comment (alistarle) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md]: Can't we point to a more recent version of the cli ?

```suggestion
You can find more informations on this tool with this guide : [OpenStack CLI](https://docs.openstack.org/python-openstackclient/latest/)
```

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md [hunk 7]
```diff
@@ -0,0 +1,167 @@
...
+Ce guide vous montrera comment émettre un jeton OpenStack, l'utiliser pour les actions que vous souhaitez effectuer et comment révoquer un jeton.
+
+## Prérequis 
+
+- Être connecté à l’[espace client OVHcloud](https://www.ovh.com/auth/?action=gotomanager&from=https://www.ovh.com/fr/&ovhSubsidiary=fr){.external}.
+- Ce guide nécessite l'installation de l'outil OpenStack CLI sur votre machine.
+
+> [!primary]
+>
+> Retrouvez plus d'informations sur cet outil dans la [documentation OpenStack CLI](https://docs.openstack.org/newton/user-guide/cli.html).
```
Comment (alistarle) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md]:
```suggestion
> Retrouvez plus d'informations sur cet outil dans la [documentation OpenStack CLI](https://docs.openstack.org/python-openstackclient/latest/).
```

**Review by alistarle — CHANGES_REQUESTED** [review]
Very nice guide, I think we can just update some doc URL and it will be good :)

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md (hunk 5 above)
Comment (alistarle) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.en-gb.md]:
```suggestion
However, if you perform too much actions in a short time, some Openstack actions will fall in error due to too much API Calls. Current limit is 60 token creation per minutes and per Openstack user, if you go above this limit, authentication endpoint will answer HTTP 429 error.
```

File: pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md [hunk 8]
```diff
@@ -0,0 +1,167 @@
...
+
+- **Jeton (*token*)** : une chaîne de caractères unique utilisée pour s'authentifier et accéder aux ressources. L'utilisateur le demande en entrant ses informations d'identification (détails de connexion) dans l'API d'authentification. Le jeton est généré et est valable pendant 24 heures.
+
+- **OpenRC** : Pour améliorer l'efficacité des interactions avec le service d'identité via le client OpenStack, OpenStack prend en charge des scripts d'environnement client simples également connus sous le nom de fichiers OpenRC. Il s'agit de fichiers contenant des options communes à tous les clients, mais supportant également des options uniques.
+
+### Problématique
+
+La plupart des demandes envoyées à l'API OpenStack doivent suivre une procédure d'autorisation qui implique la génération d'un jeton et sa validation.
+
+Cependant, si vous effectuez trop d'actions en peu de temps, certaines actions OpenStack tomberont en erreur en raison d'un trop grand nombre d'appels à l'API.
```
Comment (alistarle) [inline pages/platform/public-cloud/using_openstack_tokens_for_multiple_calls/guide.fr-fr.md]:
```suggestion
Cependant, si vous effectuez trop d'actions en peu de temps, certaines actions OpenStack tomberont en erreur en raison d'un trop grand nombre d'appels à l'API. La limite actuelle est de 60 création de jeton par minutes par utilisateur, l'API d'authentification retournera des erreurs HTTP 429 au delà de cette limite.
```

**Comment by OVH-Team-Guides** [comment]
Thank you for your contribution @thomasrts
